version: '4'

services:

  nginx:
    image: nginx:1.29-alpine-slim
    ports:
      - "8080:80"
    volumes:
      - ./public/:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:8.4.8-fpm-alpine
    volumes:
      - ./public:/var/www/html
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
